image: golang:latest

compile_alitecs-adr:
    only:
        - master
    stage: build
    script:
        - cd alitecs-adr
        - env GOOS=linux GOARCH=amd64 go build
    artifacts:
        name: binary
        paths:
        - alitecs-adr/alitecs-adr

compile_alitecs-rn2483-adr:
    only:
        - master
    stage: build
    script:
        - cd alitecs-rn2483-adr
        - env GOOS=linux GOARCH=amd64 go build
    artifacts:
        name: binary
        paths:
        - alitecs-rn2483-adr/alitecs-rn2483-adr